# Generated by Django 4.2.3 on 2023-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonos', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('horarios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntasfrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.CharField(max_length=200)),
                ('repuestas', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='especializacion',
            options={'verbose_name': 'Especialización', 'verbose_name_plural': 'Especializaciones'},
        ),
        migrations.AddField(
            model_name='profesionales',
            name='m_especializacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
    ]
