# Generated by Django 4.2.3 on 2023-08-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0002_contactos_preguntasfrecuentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='matricula',
            field=models.IntegerField(max_length=50),
        ),
    ]
