# Generated by Django 4.2.3 on 2023-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0003_alter_profesionales_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('documento', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Preguntasfrecuentes',
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
