# Generated by Django 4.2.3 on 2023-08-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0004_paciente_delete_preguntasfrecuentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contrasena1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='contrasena2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
