# Generated by Django 4.2.3 on 2023-08-30 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0007_paciente_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='username',
        ),
    ]
