# Generated by Django 4.2.3 on 2023-08-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0008_remove_paciente_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Q&A',
                'verbose_name_plural': 'Preguntas frecuentes',
            },
        ),
        migrations.DeleteModel(
            name='Especializacion',
        ),
    ]
