# Generated by Django 4.2.3 on 2023-08-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0009_preguntasfrecuentes_delete_especializacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='respuesta',
            field=models.CharField(max_length=500),
        ),
    ]
